# Copyright 2025 Ismail Çağan Yılmaz (https://github.com/milleniumkid)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Altinkaya Account",
    "summary": "Accounting Extension for Altinkaya Enclosures",
    "version": "16.0.1.6.0",
    "website": "https://github.com/altinkaya-opensource/odoo-addons",
    "author": "Ismail Çağan Yılmaz, Altinkaya Enclosures",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "base",
        "account",
        "sale",
        "stock",
        "sale_stock",
        "purchase",
        "delivery",
        "account_check",
        "base_partner_sequence",
        "account_reconcile_oca",
        "account_credit_control",
        "payment_iyzico_altinkaya",
        "account_billing_point",
        "account_invoice_pricelist",
        "altinkaya_base",
        "account_financial_risk",
        "currency_rate_turkey",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/product_pricelist_view.xml",
        "views/account_move_view.xml",
        "views/partner_view.xml",
        "views/company_view.xml",
        "views/account_invoice_report_view.xml",
        "views/res_currency_rate_view.xml",
        "views/account_bank_statement_line_view.xml",
        "views/account_reconcile_model_view.xml",
        "views/account_account_reconcile.xml",
        "views/account_move_line_view.xml",
        "views/res_config_settings.xml",
        "views/credit_control_policy_view.xml",
        "wizards/change_partner_accounts.xml",
        "wizards/create_currency_difference_invoice.xml",
        "wizards/create_currency_valuation_move.xml",
        "wizards/currency_reconcile_fix_wizard.xml",
        "wizards/import_fee_accrual_wizard.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "altinkaya_account/static/src/js/widgets/patch_reconcile_widget.esm.js",
            "altinkaya_account/static/src/xml/reconcile.xml",
        ],
    },
    "external_dependencies": {"python": ["openpyxl"]},
}
