from odoo import fields, models


class StockQuantPackage(models.Model):
    _inherit = "stock.quant.package"

    label = fields.Binary(
        help="Label of the package, generated by FedEx",
        attachment=True,
        readonly=True,
        copy=False,
    )
    label_filename = fields.Char(readonly=True, copy=False)
