{
    "name": "Altinkaya Stock",
    "version": "16.0.0.1.0",
    "website": "https://github.com/altinkaya-opensource/odoo-addons",
    "license": "LGPL-3",
    "author": "Ahmet Altınışık,OnurUgur,Codequarters,Yavuz Avcı,Altinkaya Enclosures",
    "category": "Stock",
    "summary": "add specialized stock extensions",
    "depends": [
        "hr",
        "stock",
        "sale_stock",
        "html_text",
        "delivery",
        "delivery_integration_base",
        "altinkaya_sales",
        "barcodes_generator_product",
        "partner_ranking",
        "stock_inventory",
        "stock_available_unreserved",
    ],
    "data": [
        "views/stock_quant_view.xml",
        "views/stock_picking_views.xml",
        "views/stock_view.xml",
        "views/stock_location_view.xml",
        "views/stock_location_route_views.xml",
        "views/sale_view.xml",
        "views/product_views.xml",
        "views/delivery_carrier_views.xml",
        "wizard/wizard_create_procurement_move.xml",
        "wizard/wizard_make_mts_move.xml",
        "wizard/wizard_update_unreserved_quants.xml",
        "views/stock_warehouse_orderpoint_view.xml",
        "views/mrp_production_view.xml",
        "security/security_group.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "auto_install": False,
}
